name: E2E test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:
  e2etest:
    uses: shopware/github-actions/.github/workflows/e2e.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
      e2ePath: tests/acceptance
      e2eTestFramework: playwright
      shopwareVersion: trunk